# Generated by Django 5.1 on 2026-04-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(choices=[('announcement', 'Announcement'), ('award', 'Award'), ('community', 'Community'), ('match', 'Match'), ('roster', 'Roster'), ('update', 'Update')], default='announcement', max_length=50)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Use this if not uploading a file')),
                ('published_at', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
