# Generated by Django 5.1 on 2026-04-16 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('ingame_username', models.CharField(max_length=100)),
                ('real_name', models.CharField(blank=True, max_length=150)),
                ('game', models.CharField(choices=[('rocket_league', 'Rocket League'), ('valorant', 'Valorant'), ('fortnite', 'Fortnite')], max_length=50)),
                ('role', models.CharField(choices=[('player', 'Player'), ('captain', 'Captain'), ('coach', 'Coach'), ('substitute', 'Substitute'), ('content_creator', 'Content Creator')], default='player', max_length=30)),
                ('rank', models.CharField(max_length=100)),
                ('discord_username', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('bio', models.TextField(blank=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team')),
            ],
            options={
                'ordering': ['game', 'role', 'username'],
            },
        ),
    ]
