# Generated by Django 5.1 on 2026-04-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotlightslide',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='image', max_length=10),
        ),
    ]
