# Generated by Django 5.1 on 2026-04-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('ingame_username', models.CharField(max_length=100)),
                ('game', models.CharField(choices=[('rocket_league', 'Rocket League'), ('valorant', 'Valorant'), ('fortnite', 'Fortnite')], max_length=50)),
                ('discord_username', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
