from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='wilaya',
            field=models.CharField(
                blank=True,
                choices=[
                    ('01', 'Adrar'),
                    ('02', 'Chlef'),
                    ('03', 'Laghouat'),
                    ('04', 'Oum El Bouaghi'),
                    ('05', 'Batna'),
                    ('06', 'Béjaïa'),
                    ('07', 'Biskra'),
                    ('08', 'Béchar'),
                    ('09', 'Blida'),
                    ('10', 'Bouira'),
                    ('11', 'Tamanrasset'),
                    ('12', 'Tébessa'),
                    ('13', 'Tlemcen'),
                    ('14', 'Tiaret'),
                    ('15', 'Tizi Ouzou'),
                    ('16', 'Alger'),
                    ('17', 'Djelfa'),
                    ('18', 'Jijel'),
                    ('19', 'Sétif'),
                    ('20', 'Saïda'),
                    ('21', 'Skikda'),
                    ('22', 'Sidi Bel Abbès'),
                    ('23', 'Annaba'),
                    ('24', 'Guelma'),
                    ('25', 'Constantine'),
                    ('26', 'Médéa'),
                    ('27', 'Mostaganem'),
                    ('28', "M'Sila"),
                    ('29', 'Mascara'),
                    ('30', 'Touggourt'),
                    ('31', 'Oran'),
                    ('32', 'El Bayadh'),
                    ('33', 'Illizi'),
                    ('34', 'Bordj Bou Arreridj'),
                    ('35', 'Boumerdès'),
                    ('36', 'El Tarf'),
                    ('37', 'Tindouf'),
                    ('38', 'Tissemsilt'),
                    ('39', 'El Oued'),
                    ('40', 'Khenchela'),
                    ('41', 'Souk Ahras'),
                    ('42', 'Tipaza'),
                    ('43', 'Mila'),
                    ('44', 'Aïn Defla'),
                    ('45', 'Naâma'),
                    ('46', 'Aïn Témouchent'),
                    ('47', 'Ghardaïa'),
                    ('48', 'Relizane'),
                    ('49', 'Timimoun'),
                    ('50', 'Bordj Badji Mokhtar'),
                    ('51', 'Ouled Djellal'),
                    ('52', 'Béni Abbès'),
                    ('53', 'Ain Salah'),
                    ('54', 'Ain Guezzam'),
                    ('55', 'Touggourt'),
                    ('56', 'Djanet'),
                    ('57', 'El Meghaier'),
                    ('58', 'El Menia'),
                    ('59', 'Aflou'),
                    ('60', 'Barika'),
                    ('61', 'El Kantara'),
                    ('62', 'Bir El Ater'),
                    ('63', 'El Aricha'),
                    ('64', 'Ksar Chellala'),
                    ('65', 'Ain Oussera'),
                    ('66', 'Messaad'),
                    ('67', 'Ksar El Boukhari'),
                    ('68', 'Boussaâda'),
                    ('69', 'El Abiodh Sidi Cheikh'),
                ],
                max_length=3,
            ),
        ),
    ]
