# Generated by Django 5.1 on 2026-04-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rival', models.CharField(max_length=100)),
                ('match_type', models.CharField(choices=[('tournament', 'Tournament'), ('practice', 'Practice'), ('scrim', 'Scrim'), ('friendly', 'Friendly')], default='tournament', max_length=20)),
                ('game', models.CharField(choices=[('rocket_league', 'Rocket League'), ('valorant', 'Valorant'), ('fortnite', 'Fortnite')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('score', models.CharField(blank=True, help_text='e.g. 3 — 1', max_length=20)),
                ('winner', models.CharField(blank=True, choices=[('nbl', 'NBL Esport'), ('rival', 'Rival'), ('draw', 'Draw')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
